// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/create/v1/poll_record.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollRecordDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordsId int64  `protobuf:"varint,1,opt,name=wordsId,proto3" json:"wordsId,omitempty"` //作品id
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`  //地址
}

func (x *PollRecordDTO) Reset() {
	*x = PollRecordDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_create_v1_poll_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRecordDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRecordDTO) ProtoMessage() {}

func (x *PollRecordDTO) ProtoReflect() protoreflect.Message {
	mi := &file_api_create_v1_poll_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRecordDTO.ProtoReflect.Descriptor instead.
func (*PollRecordDTO) Descriptor() ([]byte, []int) {
	return file_api_create_v1_poll_record_proto_rawDescGZIP(), []int{0}
}

func (x *PollRecordDTO) GetWordsId() int64 {
	if x != nil {
		return x.WordsId
	}
	return 0
}

func (x *PollRecordDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PollRecordVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PollRecordVO) Reset() {
	*x = PollRecordVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_create_v1_poll_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRecordVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRecordVO) ProtoMessage() {}

func (x *PollRecordVO) ProtoReflect() protoreflect.Message {
	mi := &file_api_create_v1_poll_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRecordVO.ProtoReflect.Descriptor instead.
func (*PollRecordVO) Descriptor() ([]byte, []int) {
	return file_api_create_v1_poll_record_proto_rawDescGZIP(), []int{1}
}

func (x *PollRecordVO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPollRecordDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`         //用户地址
	WordsId []int64 `protobuf:"varint,2,rep,packed,name=wordsId,proto3" json:"wordsId,omitempty"` //作品地址列表
}

func (x *ListPollRecordDTO) Reset() {
	*x = ListPollRecordDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_create_v1_poll_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPollRecordDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPollRecordDTO) ProtoMessage() {}

func (x *ListPollRecordDTO) ProtoReflect() protoreflect.Message {
	mi := &file_api_create_v1_poll_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPollRecordDTO.ProtoReflect.Descriptor instead.
func (*ListPollRecordDTO) Descriptor() ([]byte, []int) {
	return file_api_create_v1_poll_record_proto_rawDescGZIP(), []int{2}
}

func (x *ListPollRecordDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListPollRecordDTO) GetWordsId() []int64 {
	if x != nil {
		return x.WordsId
	}
	return nil
}

type ListPollRecordVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PollRecordInfo []*PollRecordInfo `protobuf:"bytes,1,rep,name=pollRecordInfo,proto3" json:"pollRecordInfo,omitempty"`
}

func (x *ListPollRecordVO) Reset() {
	*x = ListPollRecordVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_create_v1_poll_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPollRecordVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPollRecordVO) ProtoMessage() {}

func (x *ListPollRecordVO) ProtoReflect() protoreflect.Message {
	mi := &file_api_create_v1_poll_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPollRecordVO.ProtoReflect.Descriptor instead.
func (*ListPollRecordVO) Descriptor() ([]byte, []int) {
	return file_api_create_v1_poll_record_proto_rawDescGZIP(), []int{3}
}

func (x *ListPollRecordVO) GetPollRecordInfo() []*PollRecordInfo {
	if x != nil {
		return x.PollRecordInfo
	}
	return nil
}

type PollRecordInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           //点赞id
	WordsId int64  `protobuf:"varint,2,opt,name=wordsId,proto3" json:"wordsId,omitempty"` //作品id
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`  //地址
}

func (x *PollRecordInfo) Reset() {
	*x = PollRecordInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_create_v1_poll_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollRecordInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRecordInfo) ProtoMessage() {}

func (x *PollRecordInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_create_v1_poll_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRecordInfo.ProtoReflect.Descriptor instead.
func (*PollRecordInfo) Descriptor() ([]byte, []int) {
	return file_api_create_v1_poll_record_proto_rawDescGZIP(), []int{4}
}

func (x *PollRecordInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollRecordInfo) GetWordsId() int64 {
	if x != nil {
		return x.WordsId
	}
	return 0
}

func (x *PollRecordInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_api_create_v1_poll_record_proto protoreflect.FileDescriptor

var file_api_create_v1_poll_record_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x6f, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x43, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54,
	0x4f, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x56, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x49, 0x64, 0x22, 0x59,
	0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x56, 0x4f, 0x12, 0x45, 0x0a, 0x0e, 0x70, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x70, 0x6f, 0x6c, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x54, 0x0a, 0x0e, 0x50, 0x6f, 0x6c,
	0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x6f,
	0x72, 0x64, 0x73, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32,
	0xcd, 0x02, 0x0a, 0x0a, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x4d,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54, 0x4f,
	0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x4f, 0x12, 0x4d, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54, 0x4f, 0x1a,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x4f, 0x12, 0x4c, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54, 0x4f, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6c, 0x6c,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x53, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x54, 0x4f, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x4f, 0x42,
	0x35, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2d, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_create_v1_poll_record_proto_rawDescOnce sync.Once
	file_api_create_v1_poll_record_proto_rawDescData = file_api_create_v1_poll_record_proto_rawDesc
)

func file_api_create_v1_poll_record_proto_rawDescGZIP() []byte {
	file_api_create_v1_poll_record_proto_rawDescOnce.Do(func() {
		file_api_create_v1_poll_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_create_v1_poll_record_proto_rawDescData)
	})
	return file_api_create_v1_poll_record_proto_rawDescData
}

var file_api_create_v1_poll_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_create_v1_poll_record_proto_goTypes = []interface{}{
	(*PollRecordDTO)(nil),     // 0: api.create.v1.PollRecordDTO
	(*PollRecordVO)(nil),      // 1: api.create.v1.PollRecordVO
	(*ListPollRecordDTO)(nil), // 2: api.create.v1.ListPollRecordDTO
	(*ListPollRecordVO)(nil),  // 3: api.create.v1.ListPollRecordVO
	(*PollRecordInfo)(nil),    // 4: api.create.v1.PollRecordInfo
}
var file_api_create_v1_poll_record_proto_depIdxs = []int32{
	4, // 0: api.create.v1.ListPollRecordVO.pollRecordInfo:type_name -> api.create.v1.PollRecordInfo
	0, // 1: api.create.v1.PollRecord.CreatePollRecord:input_type -> api.create.v1.PollRecordDTO
	0, // 2: api.create.v1.PollRecord.DeletePollRecord:input_type -> api.create.v1.PollRecordDTO
	0, // 3: api.create.v1.PollRecord.GetPollRecord:input_type -> api.create.v1.PollRecordDTO
	2, // 4: api.create.v1.PollRecord.ListPollRecord:input_type -> api.create.v1.ListPollRecordDTO
	1, // 5: api.create.v1.PollRecord.CreatePollRecord:output_type -> api.create.v1.PollRecordVO
	1, // 6: api.create.v1.PollRecord.DeletePollRecord:output_type -> api.create.v1.PollRecordVO
	4, // 7: api.create.v1.PollRecord.GetPollRecord:output_type -> api.create.v1.PollRecordInfo
	3, // 8: api.create.v1.PollRecord.ListPollRecord:output_type -> api.create.v1.ListPollRecordVO
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_create_v1_poll_record_proto_init() }
func file_api_create_v1_poll_record_proto_init() {
	if File_api_create_v1_poll_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_create_v1_poll_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRecordDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_create_v1_poll_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRecordVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_create_v1_poll_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPollRecordDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_create_v1_poll_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPollRecordVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_create_v1_poll_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollRecordInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_create_v1_poll_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_create_v1_poll_record_proto_goTypes,
		DependencyIndexes: file_api_create_v1_poll_record_proto_depIdxs,
		MessageInfos:      file_api_create_v1_poll_record_proto_msgTypes,
	}.Build()
	File_api_create_v1_poll_record_proto = out.File
	file_api_create_v1_poll_record_proto_rawDesc = nil
	file_api_create_v1_poll_record_proto_goTypes = nil
	file_api_create_v1_poll_record_proto_depIdxs = nil
}
